version: '3.8'
services:
  app:
    build: ./app
    container_name: app_container
    ports:
      - '5173:5173'
    stdin_open: true

  server:
    build: ./server
    container_name: server_container
    ports:
      - '8765:8765'
    volumes:
      - ./server:/app
      - ./app/node_modules